---
  - name: Make sure ulimit is set for user
    lineinfile:
      path: "{{HOME_DIR}}/.profile"
      state: present
      regexp: "echo ulimit -n {{ULIMITFILES}}"
      line: "echo ulimit -n {{ULIMITFILES}}"
  - name: Make sure system limits are set
    blockinfile:
      path: "/etc/security/limits.conf"
      state: present
      block: |
        ubuntu          soft    memlock         unlimited
        ubuntu          hard    memlock         unlimited
        ubuntu          soft    nofile          {{ULIMITFILES}}
        ubuntu          hard    nofile          {{ULIMITFILES}}
        ubuntu          soft    nproc           {{ULIMITFILES}}
        ubuntu          hard    nproc           {{ULIMITFILES}}
      owner: root
      group: root
      mode: '0644'
    become: yes
  - name: Install Java 1.8 and some basic dependencies
    become: yes
    apt:
      name:
        - unzip
        - openjdk-8-jdk
      update_cache: yes
      cache_valid_time: 3600
      state: present
      autoclean: yes
  - name: Create new run directory
    file:
      path: "{{RUN_HOME}}"
      state: absent
  - file:
      path: "{{RUN_HOME}}"
      state: directory
      mode: '0755'
  - name: Unarchive downloaded file
    unarchive:
      src: "{{GATLING_DOWNLOAD_LINK}}"
      dest: "{{RUN_HOME}}"
      remote_src: yes
  - name: Tuning gatling runner memory
    replace:
      path: "{{GATLING_RUNNER}}"
      regexp: "-Xmx1G"
      replace: "-Xms{{GATLING_MEMORY}} -Xmx{{GATLING_MEMORY}}"
  - name: Tuning gatling configuration lower bound
    replace:
      path: "{{GATLING_CONF}}"
      regexp: "#lowerBound = 800"
      replace: "lowerBound = {{GATLING_REQ_LOWER_BOUND}}"
  - name: Tuning gatling configuration higher bound
    replace:
      path: "{{GATLING_CONF}}"
      regexp: "#higherBound = 1200"
      replace: "higherBound = {{GATLING_REQ_HIGHER_BOUND}}"
  - name: Tuning gatling configuration enabled GA
    replace:
      path: "{{GATLING_CONF}}"
      regexp: "#enableGA = true"
      replace: "enableGA = {{GATLING_ENABLE_GA}}"
  - name: Tuning gatling configuration max retry
    replace:
      path: "{{GATLING_CONF}}"
      regexp: "#maxRetry = 2"
      replace: "maxRetry = {{GATLING_MAX_RETRY}}"
  - name: Tuning gatling configuration request timeout
    replace:
      path: "{{GATLING_CONF}}"
      regexp: "#requestTimeout = 60000"
      replace: "requestTimeout = {{GATLING_REQ_TIMEOUT}}"
  - name: Gatling scenario scala files
    copy:
      src: "{{item}}"
      dest: "{{GATLING_SIMULATIONS_DIR}}"
    with_fileglob:
      - "{{playbook_dir}}/../{{SIMULATION_NAME}}/*.scala"
  - name: Gatling scenario json files
    copy:
      src: "{{item}}"
      dest: "{{GATLING_RESOURCES_DIR}}"
    with_fileglob:
      - "{{playbook_dir}}/../{{SIMULATION_NAME}}/*.json"
  - name: Replace hostname in scenario files
    replace:
      path: "{{GATLING_SIMULATIONS_DIR}}/{{SIMULATION_NAME}}.scala"
      regexp: "_namesuffix"
      replace: "_{{inventory_hostname}}"
