---
  - name: Execute gatling job scripts and waiting 30 seconds
    shell: "nohup {{GATLING_RUNNER}} -nr -s {{SIMULATION_NAME}} > {{RUN_HOME}}/run.log 2>&1 &"
  - pause:
      seconds: 30
  - name: Gatlings started
    debug: 
      msg: "Ansible started {{SIMULATION_NAME}} gatling simulation"
