---
  - name: Move directory
    command: "mv {{REMOTE_GATHER_REPORTS_DIR}} {{REMOTE_RESULT_DIR}}"
  - name: Tuning gatling runner memory
    replace:
      path: "{{REMOTE_GATLING_RUNNER}}"
      regexp: "-Xmx1G"
      replace: "-Xms{{GATLING_MEMORY}} -Xmx{{GATLING_MEMORY}}"
  - name: Tuning gatling configuration (lower bound, higher bound, enabled GA, max retry, request timeout)
    replace:
      path: "{{REMOTE_GATLING_CONF}}"
      regexp: "#lowerBound = 800"
      replace: "lowerBound = {{GATLING_REQ_LOWER_BOUND}}"
  - replace:
      path: "{{REMOTE_GATLING_CONF}}"
      regexp: "#higherBound = 1200"
      replace: "higherBound = {{GATLING_REQ_HIGHER_BOUND}}"
  - replace:
      path: "{{REMOTE_GATLING_CONF}}"
      regexp: "#enableGA = true"
      replace: "enableGA = {{GATLING_ENABLE_GA}}"
  - replace:
      path: "{{REMOTE_GATLING_CONF}}"
      regexp: "#maxRetry = 2"
      replace: "maxRetry = {{GATLING_MAX_RETRY}}"
  - replace:
      path: "{{REMOTE_GATLING_CONF}}"
      regexp: "#requestTimeout = 60000"
      replace: "requestTimeout = {{GATLING_REQ_TIMEOUT}}"
  - name: Execute gatling report script and waiting 30 seconds
    shell: "{{REMOTE_GATLING_RUNNER}} -ro reports"
  - pause:
      seconds: 30
  - name: Gatlings started
    debug: 
      msg: "Ansible started {{SIMULATION_NAME}} gatling simulation"